/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JInternalFrame;
/**
 *
 * @author Hello Kiên
 */
public class TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    QuanLyMatHang qlmh;
    QuanLyKhachHang qlkh;
    QuanLyBanHang qlbh;
    Ghi_chu gc;
    
    public TrangChu() {
        initComponents();
        setLocationRelativeTo(null);
        
        gc = new Ghi_chu();
        JDesktop.add(gc);
        gc.setVisible(true);
        gc.setLocation((JDesktop.getWidth() - gc.getWidth()) / 2, (JDesktop.getHeight() - gc.getHeight()) / 2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        JDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        QLMH = new javax.swing.JMenu();
        QLKH = new javax.swing.JMenu();
        QLBH = new javax.swing.JMenu();
        GhiChu = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Bán Hàng");

        javax.swing.GroupLayout JDesktopLayout = new javax.swing.GroupLayout(JDesktop);
        JDesktop.setLayout(JDesktopLayout);
        JDesktopLayout.setHorizontalGroup(
            JDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );
        JDesktopLayout.setVerticalGroup(
            JDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );

        QLMH.setText("Quản lý mặt hàng");
        QLMH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QLMHMouseClicked(evt);
            }
        });
        QLMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLMHActionPerformed(evt);
            }
        });
        jMenuBar1.add(QLMH);

        QLKH.setText("Quản lý khách hàng");
        QLKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QLKHMouseClicked(evt);
            }
        });
        jMenuBar1.add(QLKH);

        QLBH.setText("Quản lý bán hàng");
        QLBH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QLBHMouseClicked(evt);
            }
        });
        jMenuBar1.add(QLBH);

        GhiChu.setText("Hướng dẫn sử dụng");
        GhiChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GhiChuMouseClicked(evt);
            }
        });
        jMenuBar1.add(GhiChu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QLMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLMHActionPerformed
       
    }//GEN-LAST:event_QLMHActionPerformed

    private void QLMHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QLMHMouseClicked
        for (JInternalFrame jif : JDesktop.getAllFrames()) {
            jif.dispose();
        }
        if (qlmh == null || qlmh.isClosed()) {
            qlmh = new QuanLyMatHang();
            JDesktop.add(qlmh);
            qlmh.setVisible(true);
            qlmh.setLocation((JDesktop.getWidth() -qlmh.getWidth())/2,
                (JDesktop.getHeight() -qlmh.getHeight())/2);

        } else {
            qlmh.setVisible(true);
        }
    }//GEN-LAST:event_QLMHMouseClicked

    private void QLKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QLKHMouseClicked
        for (JInternalFrame jif : JDesktop.getAllFrames()) {
            jif.dispose();
        }
        if (qlkh == null || qlkh.isClosed()) {
            qlkh = new QuanLyKhachHang();
            JDesktop.add(qlkh);
            qlkh.setVisible(true);
            qlkh.setLocation((JDesktop.getWidth() -qlkh.getWidth())/2,
                (JDesktop.getHeight() -qlkh.getHeight())/2);
        } else {
            qlkh.setVisible(true);
        }
    }//GEN-LAST:event_QLKHMouseClicked

    private void QLBHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QLBHMouseClicked
        for (JInternalFrame jif : JDesktop.getAllFrames()) {
            jif.dispose();
        }
        if (qlbh == null || qlbh.isClosed()) {
            qlbh = new QuanLyBanHang();
            JDesktop.add(qlbh);
            qlbh.setVisible(true);
            qlbh.setLocation((JDesktop.getWidth() -qlbh.getWidth())/2,
                (JDesktop.getHeight() -qlbh.getHeight())/2);
        } else {
            qlbh.setVisible(true);
        }
    }//GEN-LAST:event_QLBHMouseClicked

    private void GhiChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GhiChuMouseClicked
        for (JInternalFrame jif : JDesktop.getAllFrames()) {
            jif.dispose();
        }
        if (gc == null || gc.isClosed()) {
            gc = new Ghi_chu();
            JDesktop.add(gc);
            gc.setVisible(true);
            gc.setLocation((JDesktop.getWidth() -gc.getWidth())/2,
                (JDesktop.getHeight() -gc.getHeight())/2);
        } else {
            gc.setVisible(true);
        }
    }//GEN-LAST:event_GhiChuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu GhiChu;
    private javax.swing.JDesktopPane JDesktop;
    private javax.swing.JMenu QLBH;
    private javax.swing.JMenu QLKH;
    private javax.swing.JMenu QLMH;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
